In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [9]:
df.dropna(how='any', inplace=True)

In [10]:
len(df)

7032

In [11]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [13]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [14]:
y=df.Churn.values

In [15]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [16]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(7032,), dtype=object)

In [17]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [18]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [19]:
X.head(1)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [20]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [21]:
len(X_train)

5274

In [22]:
len(X_test)

1758

In [23]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [24]:
X_train_sc

array([[-0.4423203 ,  0.4632403 , -1.50321559, ..., -0.52777406,
        -0.71466209, -0.54213984],
       [-0.4423203 , -0.67821843, -1.50985955, ...,  1.8947502 ,
        -0.71466209, -0.54213984],
       [ 2.26080514, -0.84128397,  0.63115493, ..., -0.52777406,
        -0.71466209,  1.84454255],
       ...,
       [-0.4423203 , -0.14825545, -0.15283175, ..., -0.52777406,
        -0.71466209,  1.84454255],
       [-0.4423203 , -0.63745205, -0.96837722, ...,  1.8947502 ,
        -0.71466209, -0.54213984],
       [-0.4423203 , -1.04511588,  0.54644451, ..., -0.52777406,
        -0.71466209, -0.54213984]], shape=(5274, 30))

In [25]:
X_test_sc

array([[-0.4423203 ,  0.01481009, -1.34708265, ..., -0.52777406,
        -0.71466209, -0.54213984],
       [-0.4423203 , -1.2489478 ,  0.69261152, ..., -0.52777406,
         1.39926269, -0.54213984],
       [-0.4423203 , -0.5151529 , -0.49167345, ..., -0.52777406,
        -0.71466209,  1.84454255],
       ...,
       [-0.4423203 ,  0.9524369 , -0.17608559, ...,  1.8947502 ,
        -0.71466209, -0.54213984],
       [-0.4423203 ,  1.15626882,  0.29895719, ..., -0.52777406,
        -0.71466209, -0.54213984],
       [-0.4423203 , -0.88205035, -0.3670993 , ..., -0.52777406,
         1.39926269, -0.54213984]], shape=(1758, 30))

#### kNN Classifier

In [26]:
# Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

# Initiating the classifier
model = KNeighborsClassifier()

# Passing the data to classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [27]:
y_pred = model.predict(X_test_sc)

In [28]:
y_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'],
      shape=(1758,), dtype=object)

In [29]:
y_test

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'],
      shape=(1758,), dtype=object)

In [30]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred)*100)

76.56427758816837

#### New data prediction

In [31]:
X_test_sc

array([[-0.4423203 ,  0.01481009, -1.34708265, ..., -0.52777406,
        -0.71466209, -0.54213984],
       [-0.4423203 , -1.2489478 ,  0.69261152, ..., -0.52777406,
         1.39926269, -0.54213984],
       [-0.4423203 , -0.5151529 , -0.49167345, ..., -0.52777406,
        -0.71466209,  1.84454255],
       ...,
       [-0.4423203 ,  0.9524369 , -0.17608559, ...,  1.8947502 ,
        -0.71466209, -0.54213984],
       [-0.4423203 ,  1.15626882,  0.29895719, ..., -0.52777406,
        -0.71466209, -0.54213984],
       [-0.4423203 , -0.88205035, -0.3670993 , ..., -0.52777406,
         1.39926269, -0.54213984]], shape=(1758, 30))

In [32]:
X_test.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [33]:
data = [[0, 2, 87, 178, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]]

In [34]:
data_sc = sc.transform(data)

single = model.predict(data_sc)

print(single)

['Yes']

c:\Users\vikas\OneDrive\Desktop\Data-Science-and-AI-Masters-2025\revision\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [35]:
data_sc = sc.transform(data)

single = model.predict_proba(data_sc)

print(single)

[[0.2 0.8]]

c:\Users\vikas\OneDrive\Desktop\Data-Science-and-AI-Masters-2025\revision\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

#### Decision Tree Classifier

In [36]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [37]:
y_pred_dt = model_dt.predict(X_test_sc)

In [38]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_dt)*100)

73.89078498293516

#### Random Forest Classifier

In [39]:
# Call the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Initiating the classifier
model_rf = RandomForestClassifier(n_estimators=200)

# Passing the data to classifier
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [40]:
y_pred_rf = model_rf.predict(X_test_sc)

In [41]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_rf)*100)

78.5551763367463

In [42]:
from sklearn.metrics import classification_report

knn_report = classification_report(y_test, y_pred)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [43]:
print('knn report', knn_report)

knn report               precision    recall  f1-score   support

          No       0.83      0.85      0.84      1285
         Yes       0.57      0.54      0.55       473

    accuracy                           0.77      1758
   macro avg       0.70      0.69      0.70      1758
weighted avg       0.76      0.77      0.76      1758

In [44]:
print('dt report', dt_report)

dt report               precision    recall  f1-score   support

          No       0.82      0.82      0.82      1285
         Yes       0.51      0.53      0.52       473

    accuracy                           0.74      1758
   macro avg       0.67      0.67      0.67      1758
weighted avg       0.74      0.74      0.74      1758

In [45]:
print('rf report', rf_report)

rf report               precision    recall  f1-score   support

          No       0.83      0.89      0.86      1285
         Yes       0.62      0.51      0.56       473

    accuracy                           0.79      1758
   macro avg       0.73      0.70      0.71      1758
weighted avg       0.78      0.79      0.78      1758

#### Naive Bayes Classifier

In [46]:
# Call the Random Forest Classifier
from sklearn.naive_bayes import BernoulliNB

# Initiating the classifier
model_nb = BernoulliNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, y_train)

# Predictions
y_pred_nb = model_nb.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_nb)*100)

73.09442548350398

#### SVM Classifier

In [47]:
# Call the Random Forest Classifier
from sklearn.svm import SVC

# Initiating the classifier
model_svc = SVC()

# Passing the data to classifier
model_svc.fit(X_train_sc, y_train)

# Predictions
y_pred_svc = model_svc.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_svc)*100)

80.43230944254836

In [48]:
svc_report = classification_report(y_test, y_pred_svc)
print(svc_report)

              precision    recall  f1-score   support

          No       0.83      0.92      0.87      1285
         Yes       0.69      0.50      0.58       473

    accuracy                           0.80      1758
   macro avg       0.76      0.71      0.73      1758
weighted avg       0.79      0.80      0.79      1758

#### Logistic Regression Classifier

In [49]:
# Call the Random Forest Classifier
from sklearn.linear_model import LogisticRegression

# Initiating the classifier
model_lr = LogisticRegression()

# Passing the data to classifier
model_lr.fit(X_train_sc, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_lr)*100)

81.22866894197952

In [50]:
lr_report = classification_report(y_test, y_pred_lr)
print(lr_report)

              precision    recall  f1-score   support

          No       0.85      0.90      0.88      1285
         Yes       0.68      0.57      0.62       473

    accuracy                           0.81      1758
   macro avg       0.77      0.74      0.75      1758
weighted avg       0.81      0.81      0.81      1758

In [51]:
print("The End")

The End